---
# reboot.yml
# Simple playbook to reboot Mac machines

- name: Reboot Mac Machines
  hosts: "{{ target_hosts | default('all') }}"
  remote_user: "{{ admin_user | default('automation_user') }}"
  become_user: root
  become: yes
  gather_facts: no

  tasks:
    - name: Reboot Mac
      command: /sbin/shutdown -r now
      become_user: root
      become: yes
      ignore_errors: yes

